"""Guards the one-source-of-truth version rule.

Every module re-exports the generated apis/_version.py value. These tests fail
if a module starts hardcoding its own version again, which is how the previous
1.4.0 / 1.3.5 / 1.1.3 drift happened.
"""

import re
from pathlib import Path

import pytest

import apis
from apis import base, modrinth_api

REPO_ROOT = Path(__file__).resolve().parent.parent

REEXPORT = 'from ._version import __version__'
HARDCODED = re.compile(r'^__version__\s*=', re.MULTILINE)
GENERATED_HEADER = 'Generated by scripts/update_version.py'
PEP440 = re.compile(
    r'^\d+\.\d+\.\d+'
    r'((a|b|rc)\d+)?'
    r'(\.post\d+)?'
    r'(\.dev\d+)?'
    r'(\+[a-z0-9]+(\.[a-z0-9]+)*)?$')

API_MODULES = [
    'apis/__init__.py',
    'apis/base.py',
    'apis/modrinth_api.py',
]


def read(relative_path):
    return (REPO_ROOT / relative_path).read_text()


def test_all_api_modules_report_the_same_version():
    assert apis.__version__ == base.__version__
    assert apis.__version__ == modrinth_api.__version__


@pytest.mark.parametrize('relative_path', API_MODULES)
def test_api_modules_reexport_the_generated_version(relative_path):
    content = read(relative_path)
    assert REEXPORT in content, f'{relative_path} does not re-export it'


@pytest.mark.parametrize('relative_path', API_MODULES + ['main.py'])
def test_no_module_hardcodes_a_version(relative_path):
    assert not HARDCODED.search(read(relative_path)), \
        f'{relative_path} hardcodes __version__'


def test_main_py_takes_the_version_from_the_package():
    content = read('main.py')
    assert '__version__' in content.split('parser = ')[0]
    assert 'from apis import' in content


def test_generated_file_is_marked_generated():
    content = read('apis/_version.py')
    assert GENERATED_HEADER in content


def test_generated_version_looks_like_pep440():
    assert PEP440.match(apis.__version__), apis.__version__
