#!/usr/bin/env python3
"""Derive the project version from git and write apis/_version.py.

The version comes from the nearest reachable tag, so it is never edited by
hand. Commits after a tag become PEP 440 dev releases, which sort before the
next release:

    v1.4.0 on HEAD        -> 1.4.0
    v1.4.0 + 3 commits    -> 1.4.1.dev3+g3a00e22
    no tags yet           -> 0.0.1.dev30+g3a00e22

Only committed state counts, so the same commit always yields the same
version on your machine and in CI.

Usage:
    python scripts/update_version.py            rewrite apis/_version.py
    python scripts/update_version.py --print    print it without writing
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = REPO_ROOT / 'apis' / '_version.py'
UNTAGGED_BASE = '0.0.0'

GENERATED_HEADER = (
    '"""Generated by scripts/update_version.py -- do not edit by hand."""\n'
    '\n'
)


def git(*args: str) -> str:
    """Run a git command in the repo and return its stripped stdout."""
    result = subprocess.run(
        ['git', '-C', str(REPO_ROOT), *args],
        capture_output=True,
        text=True)
    if result.returncode != 0:
        raise SystemExit(
            f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def nearest_tag() -> str | None:
    """Return the closest reachable tag, or None when the repo has none."""
    result = subprocess.run(
        ['git', '-C', str(REPO_ROOT), 'describe', '--tags', '--abbrev=0'],
        capture_output=True,
        text=True)
    if result.returncode != 0:
        return None
    return result.stdout.strip() or None


def next_release(base: str) -> str:
    """Bump the last number of a release tag: 1.4.0 -> 1.4.1."""
    parts = base.split('.')
    if len(parts) != 3 or not all(part.isdigit() for part in parts):
        return base
    return '.'.join([parts[0], parts[1], str(int(parts[2]) + 1)])


def compute_version() -> str:
    """Return the PEP 440 version for the current commit."""
    tag = nearest_tag()
    if tag is None:
        base = UNTAGGED_BASE
        distance = int(git('rev-list', '--count', 'HEAD'))
    else:
        base = tag[1:] if tag.startswith('v') else tag
        distance = int(git('rev-list', '--count', f'{tag}..HEAD'))

    if distance == 0:
        return base

    sha = git('rev-parse', '--short=7', 'HEAD')
    return f'{next_release(base)}.dev{distance}+g{sha}'


def render(version: str) -> str:
    """Return the full contents of the generated version file."""
    return GENERATED_HEADER + f'__version__ = {version!r}\n'


def main() -> int:
    parser = argparse.ArgumentParser(
        description='Generate apis/_version.py from git tags.')
    parser.add_argument(
        '--print',
        dest='print_only',
        action='store_true',
        help='print the version instead of writing the file')
    args = parser.parse_args()

    version = compute_version()
    if args.print_only:
        print(version)
        return 0

    VERSION_FILE.write_text(render(version))
    print(f'wrote {VERSION_FILE} ({version})')
    return 0


if __name__ == '__main__':
    sys.exit(main())
